### ISSUE TITLE
No such file or directory: 'sblogs/default'

### ISSUE THREAD

**Issue by Jihyepark98** [facebookresearch/SemanticImageTranslation#1]
When I train this command,
 
```
python transform_dataset.py --config exp_configs/final.yaml \
                            --output generated/default \
                            --domain test \
```
 I get this error. 
```
Traceback (most recent call last):
  File "transform_dataset.py", line 79, in <module>
    ngpus=args.ngpus)
  File "/root/project/SemanticImageTranslation/utils/submit.py", line 14, in submit
    Path(f'sblogs/{folder}').mkdir(exist_ok=True)
  File "/opt/conda/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/opt/conda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'sblogs/default'
```

How to solve it?

**Comment by gcouairon** [comment]
Hello,
you should create a 'sblogs' folder at the root of the repository, so that submitit can write logs in this folder.
